---
- hosts: localhost
  gather_facts: false
  vars:
    metadata:
      name: Verify DNS
      description: >
        Verify that the DNS resolution works
      groups:
        - pre-deployment
      categories:
        - networking
        - dns
      products:
        - common
    server_to_lookup: example.com
  roles:
    - dns
