---
- hosts: all
  gather_facts: false
  vars:
    metadata:
      name: Ensure services state
      description: >
        Detect services status on the target host and fails if we find
        a failed service.
      groups:
        - prep
        - backup-and-restore
        - pre-deployment
        - pre-upgrade
        - post-deployment
        - post-upgrade
      categories:
        - systemd
        - container
        - docker
        - podman
      products:
        - common
  roles:
    - service_status
