---
# Volumes partitioning schema
# A list of dictionary.ies containing:
# - mount point(s)
# - min_size (Minimum free space required in GB)
volumes:
  - {mount: /var/lib/docker, min_size: 10}
  - {mount: /var/lib/config-data, min_size: 3}
  - {mount: /var/log, min_size: 3}
  - {mount: /usr, min_size: 5}
  - {mount: /var, min_size: 20}
  - {mount: /, min_size: 25}
