---
- job:
    description: Base validations-common job
    name: validations-common-centos-7-base
    nodeset: centos-7
    parent: base
    success-url: "reports.html"
    failure-url: "reports.html"
    pre-run:
    - tests/prepare-test-host.yml
    - zuul.d/playbooks/pre.yml
    run:
    - zuul.d/playbooks/run.yml
    timeout: 1800
    voting: true
