---
# inherits tripleo-validations/.config/molecule/config.yml
# To override default values, please take a look at the config.yml.
driver:
  name: podman

log: true

platforms:
  - name: centos
    hostname: centos
    image: centos/centos:stream8
    registry:
      url: quay.io
    dockerfile: ../../../../../.config/molecule/Dockerfile
    pkg_extras: python*-setuptools python*-pyyaml
    volumes:
      - /etc/ci/mirror_info.sh:/etc/ci/mirror_info.sh:ro
    privileged: true
    environment: &env
      http_proxy: "{{ lookup('env', 'http_proxy') }}"
      https_proxy: "{{ lookup('env', 'https_proxy') }}"
    ulimits: &ulimit
      - host
    command: /sbin/init

provisioner:
  name: ansible
  inventory:
    hosts:
      all:
        hosts:
          centos:
            ansible_python_interpreter: /usr/bin/python3
  log: true
  options:
    vvv: true
  env:
    ANSIBLE_STDOUT_CALLBACK: yaml
    ANSIBLE_ROLES_PATH: "${ANSIBLE_ROLES_PATH}:${HOME}/zuul-jobs/roles"
    ANSIBLE_LIBRARY: "${ANSIBLE_LIBRARY:-/usr/share/ansible/plugins/modules}"

scenario:
  test_sequence:
    - destroy
    - create
    - prepare
    - converge
    - verify
    - destroy

verifier:
  name: ansible
